/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:1b30db430c78e0201db1807be47e90e5:f70e0ba19f9ab0e7bf96dc93b5fc627a:d05029a6915dd3dbed03345ba5dbbeab$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string 2Untitled = "2Untitled";
		public const string AD1(1) = "AD1(1)";
		public const string AD1(2) = "AD1(2)";
		public const string AD1(3) = "AD1(3)";
		public const string AD1(4) = "AD1(4)";
		public const string AD2(1) = "AD2(1)";
		public const string AD2(2) = "AD2(2)";
		public const string AD2(3) = "AD2(3)";
		public const string AD2(4) = "AD2(4)";
		public const string AD3(1) = "AD3(1)";
		public const string AD3(4) = "AD3(4)";
		public const string AR1(1) = "AR1(1)";
		public const string AR1(2) = "AR1(2)";
		public const string AR1(3) = "AR1(3)";
		public const string AR1(4) = "AR1(4)";
		public const string RD1 = "RD1";
		public const string RD2 = "RD2";
		public const string RD3 = "RD3";
		public const string RD4 = "RD4";
		public const string RR1 = "RR1";
		public const string RR2 = "RR2";
		public const string RR3 = "RR3";
		public const string RR4 = "RR4";
		public const string SD = "SD";
		public const string SR1 = "SR1";
		public const string Untiawdatled = "Untiawdatled";
		public const string Untisdtled = "Untisdtled";
		public const string Untitled = "Untitled";
		public const string Untitled1 = "Untitled1";
		public const string Untitledawda = "Untitledawda";
		public const string Untitsefled = "Untitsefled";
		public const string WD1 = "WD1";
		public const string WD2 = "WD2";
		public const string WD3 = "WD3";
		public const string WD4 = "WD4";
		public const string WR1 = "WR1";
		public const string WR2 = "WR2";
		public const string WR3 = "WR3";
		public const string WR4 = "WR4";
		public const string Aefrh = "aefrh";
		public const string Awawdawd = "awawdawd";
		public const string Efsefef = "efsefef";
		public const string Ergerg = "ergerg";
		public const string Ghhjy = "ghhjy";
		public const string Mjndv = "mjndv";
		public const string Qwer = "qwer";
		public const string SdsfUntitled = "sdsfUntitled";
		public const string SeUntitled = "seUntitled";
		public const string SefUntitled = "sefUntitled";
		public const string SefefsefUntitled = "sefefsefUntitled";
		public const string SefsUntitled = "sefsUntitled";
		public const string SefsefUntitled = "sefsefUntitled";
		public const string Slice = "slice";
		public const string Slice04_04 = "slice04_04";
		public const string Slice05_07 = "slice05_07";
		public const string Slice08_08 = "slice08_08";
		public const string Slice103_@ = "slice103_@";
		public const string Slice118_@ = "slice118_@";
		public const string Slice11_11 = "slice11_11";
		public const string Slice12_14 = "slice12_14";
		public const string Slice17_17 = "slice17_17";
		public const string Slice19_19 = "slice19_19";
		public const string Slice2 = "slice2";
		public const string Slice20_20 = "slice20_20";
		public const string Slice22_22 = "slice22_22";
		public const string Slice24_24 = "slice24_24";
		public const string Slice25_25 = "slice25_25";
		public const string Slice26_27 = "slice26_27";
		public const string Slice27_27 = "slice27_27";
		public const string Slice28_28 = "slice28_28";
		public const string Slice29_29 = "slice29_29";
		public const string Slice32_32 = "slice32_32";
		public const string Slice33_33 = "slice33_33";
		public const string Slice34_34 = "slice34_34";
		public const string Slice35_35 = "slice35_35";
		public const string Slice38_38 = "slice38_38";
		public const string Slice39_39 = "slice39_39";
		public const string Slice42_42 = "slice42_42";
		public const string Slice44_44 = "slice44_44";
		public const string Slice46_46 = "slice46_46";
		public const string Slice47_47 = "slice47_47";
		public const string Slice48_48 = "slice48_48";
		public const string Slice49_49 = "slice49_49";
		public const string Slice50_50 = "slice50_50";
		public const string Slice52_52 = "slice52_52";
		public const string Slice53_53 = "slice53_53";
		public const string Slice54_54 = "slice54_54";
		public const string Slice55_55 = "slice55_55";
		public const string Slice56_56 = "slice56_56";
		public const string Slice57_57 = "slice57_57";
		public const string Slice58_58 = "slice58_58";
		public const string Slice59_59 = "slice59_59";
		public const string Slice60_60 = "slice60_60";
		public const string Slice62_62 = "slice62_62";
		public const string Slice63_63 = "slice63_63";
		public const string Slice64_64 = "slice64_64";
		public const string Slice65_65 = "slice65_65";
		public const string Slice66_66 = "slice66_66";
		public const string Slice70_70 = "slice70_70";
		public const string Slice71_71 = "slice71_71";
		public const string Slice74_74 = "slice74_74";
		public const string Slice76_76 = "slice76_76";
	}
}