/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:4e9e1d1bfd2dbc2efd1852e5109ad346:0cdd86a3ed40f448a42fb37faab9e7f0:8c525836dd4e460cd3915e7dea67149d$
 *
 */
namespace _2D_Game
{
	public class OldSpriteDefs
	{
		public const string Arrow = "Arrow";
		public const string BlueBar = "BlueBar";
		public const string Castle2 = "Castle2";
		public const string EmptyBars = "EmptyBars";
		public const string EnemyFront = "EnemyFront";
		public const string FighterFront = "FighterFront";
		public const string GreenBar = "GreenBar";
		public const string HealthPotion = "HealthPotion";
		public const string Mage = "Mage";
		public const string MageFront = "MageFront";
		public const string NewRedBar = "NewRedBar";
		public const string Npc = "Npc";
		public const string RedBar = "RedBar";
		public const string Seller = "Seller";
		public const string Ball = "ball";
		public const string Boundingbox = "boundingbox";
		public const string Chests32X32 = "chests_32x32";
		public const string Dragon = "dragon";
		public const string Enemy = "enemy";
		public const string LargeHealthPotion = "largeHealthPotion";
		public const string Manapotion = "manapotion";
		public const string Numbertileset = "numbertileset";
		public const string Part1Tileset = "part1_tileset";
		public const string Part2Tileset = "part2_tileset";
		public const string Projectile = "projectile";
		public const string SmallHealthpotion = "smallHealthpotion";
		public const string TargetIcon = "target_icon";
		public const string Tileset = "tileset";
	}
}